@echo OFF
@set KANZI_JAR=kanzi.jar
@set CORPUS=c:\temp\calgary
@set DEBUG=-debug

@REM run from %KANZI%\go\src\kanzi\app !!! (or change to point to exe generated by GO)

@set sources=bib book1 book2 geo news obj1 obj2 paper1 paper2 paper3 paper4 paper5 paper6 pic progc progl progp trans
@set entropy=none huffman range fpaq paq
@REM cleanup

for %%f in (%sources%) do (
     del %CORPUS%\%%f.log 2> NUL
)


for %%e in (%entropy%) do (
   @echo  ==== Entropy: %%e ==== 
   @echo  ==== Entropy: %%e ==== >> %CORPUS%\%%f.log
   
   for %%f in (%sources%) do (
     echo File: %CORPUS%\%%f
     echo File: %CORPUS%\%%f >> %CORPUS%\%%f.log
     
     @echo java implementation
     del %CORPUS%\%%f.java.knz 2> NUL
     java -cp %KANZI_JAR% kanzi.app.BlockCompressor %DEBUG% -input=%CORPUS%\%%f -output=%CORPUS%\%%f.java.knz -block=4000000 -entropy=%%e >> %CORPUS%\%%f.log
     del %CORPUS%\%%f.java.bak 2> NUL
     java -cp %KANZI_JAR% kanzi.app.BlockDecompressor %DEBUG% -input=%CORPUS%\%%f.java.knz -output=%CORPUS%\%%f.java.bak >> %CORPUS%\%%f.log
     
     @echo go implementation
     del %CORPUS%\%%f.go.knz 2> NUL
     go run BlockCompressor.go -input=%CORPUS%\%%f %DEBUG% -output=%CORPUS%\%%f.go.knz -block=4000000 -entropy=%%e >> %CORPUS%\%%f.log
     del %CORPUS%\%%f.go.bak 2> NUL
     go run BlockDecompressor.go -input=%CORPUS%\%%f.go.knz %DEBUG% -output=%CORPUS%\%%f.go.bak >> %CORPUS%\%%f.log

     @echo cross-compression
     del %CORPUS%\%%f.java.go 2> NUL
     java -cp %KANZI_JAR% kanzi.app.BlockDecompressor %DEBUG% -input=%CORPUS%\%%f.go.knz -output=%CORPUS%\%%f.java.go >> %CORPUS%\%%f.log
     del %CORPUS%\%%f.go.java 2> NUL
     go run BlockDecompressor.go %DEBUG% -input=%CORPUS%\%%f.java.knz -output=%CORPUS%\%%f.go.java >> %CORPUS%\%%f.log
   )
)

goto END

:ERROR
echo Error.

:END